# By default all the jobs will run parallely in separate VM
# 'needs' helps workflow to run jobs sequencly even though each jobs runs in separate VM
# upload/download actions help the workflow to store/dowload the artificats across the jobs(VMs)
# dragon.txt will be stored in the github even though all the VMs destroyed after the job execution
name: Generate ASCII Artwork

on: push

jobs:
    build_job_1:
        runs-on:  ubuntu-latest
        steps:
        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y
        
        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

        - name: Sleep for 30 seconds
          run: sleep 30

        - name: Upload Dragon text file # without uploading the dragon.txt file the test_job_2 will fail because it will be running on differnt VM
          uses: actions/upload-artifact@v3
          with:
            name: dragon-text-file
            path: dragon.txt
        
    test_job_2:
        needs: build_job_1 # needs will helps the workflow to run the job sequencily, even though jobs are running on differnt VM, this job will wait until build_job_1 finished
        runs-on: ubuntu-latest
        steps:
        - name: Sleep for 30 seconds
          run: sleep 30
        
        - name: Download Dragon text file # will download the artifacts uploaded in build_job_1
          uses: actions/download-artifact@v3
          with:
            name: dragon-text-file

        - name: Test File Exists
          run: grep -i "dragon" dragon.txt

    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
        
        - name: Download Dragon text file # will download the artifacts uploaded in build_job_1
          uses: actions/download-artifact@v3
          with:
            name: dragon-text-file
  
        - name: Read File
          run: cat dragon.txt
        
        - name: Deploy
          run: echo Deploying... .. .
  